#define SCREEN_STANDBY 0
#define SCREEN_MAIN 1
#define SCREEN_TUNING 2
#define SCREEN_SETUP 3

#define KEY_ONOFF 0
#define KEY_CHAN_UP 1
#define KEY_CHAN_DOWN 2
#define KEY_VOL_UP 3
#define KEY_VOL_DOWN 4
#define KEY_SETUP 5

#define PIN_RELAY 10
#define PIN_DIGIPOT 11 // 11 - CS, 12 - SDI

#define CHAN_FLOOR 2
#define CHAN_CEIL 83

#define ADDRESS_CHANNEL 0
#define ADDRESS_VOLUME 1
#define ADDRESS_BRIGHTNESS 2
#define ADDRESS_CONTRAST 3
#define ADDRESS_VERTICAL 4

#define EEPROM_OFFSET 10